// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAIVOPDJHpHHn0-gxpOgl0lHJnWq968Sn8',
    appId: '1:897773624791:android:7319da56ef41e80c067f92',
    messagingSenderId: '897773624791',
    projectId: 'lets-chat-61f76',
    storageBucket: 'lets-chat-61f76.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCMnqYtt4DG-ze4eSAc01AvfPpUPNZBhgk',
    appId: '1:897773624791:ios:3051266cf9ec3397067f92',
    messagingSenderId: '897773624791',
    projectId: 'lets-chat-61f76',
    storageBucket: 'lets-chat-61f76.appspot.com',
    iosBundleId: 'com.example.letschatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAbz3jU2VafBBj9XaP0pjKAJ62yXDQG060',
    appId: '1:897773624791:web:7d196ce433c2a655067f92',
    messagingSenderId: '897773624791',
    projectId: 'lets-chat-61f76',
    authDomain: 'lets-chat-61f76.firebaseapp.com',
    storageBucket: 'lets-chat-61f76.appspot.com',
    measurementId: 'G-HDJ9L8L038',
  );
}
